package com.darkerbox.hacktools.dfquery;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Dfquery {

	public static HashMap<String, String> dfmap;

	public static void init(){
		dfmap = new HashMap<String, String>();
		dfmap.put("d_safe_manage.exe", "d盾");
		dfmap.put("d_manage.exe", "d盾");
		dfmap.put("pc.exe", "云锁客户端");
		dfmap.put("yunsuo_agent_service.exe", "云锁服务端");
		dfmap.put("yunsuo_agent_daemon.exe", "云锁服务端");
		dfmap.put("gov_defence_daemon.exe", "govdefence(网防G01)");
		dfmap.put("gov_defence_service.exe", "govdefence(网防G01)");
		dfmap.put("aliyundun.exe", "阿里云-云盾");
		dfmap.put("alisecguard.exe", "阿里云-云盾");
		dfmap.put("aliyundunupdate.exe", "阿里云-升级服务");
		dfmap.put("aliyun_assist_service.exe", "阿里云-云监控");
		dfmap.put("baradagent.exe", "腾讯云-安全监控组件");
		dfmap.put("sgagent.exe", "腾讯云-安全监控组件");
		dfmap.put("ydservice.exe", "腾讯云-云镜主机安全");
		dfmap.put("ydlive.exe", "腾讯云-云镜主机安全");
		dfmap.put("ydedr.exe", "腾讯云-云镜主机安全");
		dfmap.put("360websafe.exe", "360主机卫士");
		dfmap.put("qhsrv.exe", "360主机卫士");
		dfmap.put("qhwebshellguard.exe", "360主机卫士");
		dfmap.put("cloudhelper.exe", "安全狗");
		dfmap.put("safedogtray.exe", "安全狗");
		dfmap.put("safedogguardcenter.exe", "安全狗");
		dfmap.put("safedogupdatecenter.exe", "安全狗");
		dfmap.put("safedogsiteapache.exe", "网站安全狗(apache)");
		dfmap.put("safedogsiteiis.exe", "网站安全狗(iis)");
		dfmap.put("safedogserverui.exe", "服务器安全狗");
		dfmap.put("hws.exe", "护卫神·入侵防护系统");
		dfmap.put("hwsd.exe", "护卫神·入侵防护系统");
		dfmap.put("hws_ui.exe", "护卫神·入侵防护系统");
		dfmap.put("hwspanel.exe", "护卫神·入侵防护系统");
		dfmap.put("Deep Security Manager.exe", "亚信DS服务端 - 安全管理");
		dfmap.put("dsa.exe", "亚信DS客户端 - 代理的主要进程");
		dfmap.put("Notifier.exe", "亚信DS客户端 - 深度安全通知程序的进程");
		dfmap.put("coreFrameworkHost.exe", "亚信DS客户端 - 反恶意软件扫描过程");
		dfmap.put("coreServiceShell.exe", "亚信DS客户端 - 反恶意软件扫描过程");
		dfmap.put("dsvp.exe", "亚信DS客户端 - 中继服务器进程");
		dfmap.put("hipsdaemon.exe", "火绒安全软件");
		dfmap.put("hipstray.exe", "火绒安全软件");
		dfmap.put("hipslog.exe", "火绒安全软件");
		dfmap.put("hipsmain.exe", "火绒安全软件");
		dfmap.put("usysdiag.exe", "火绒安全软件");
		dfmap.put("wsctrl.exe", "火绒安全软件");
		dfmap.put("qqpcrtp.exe", "腾讯电脑管家");
		dfmap.put("qqpctray.exe", "腾讯电脑管家");
		dfmap.put("qqpcnetflow.exe", "腾讯电脑管家");
		dfmap.put("qqpcrealtimespeedup.exe", "腾讯电脑管家");
		dfmap.put("360sd.exe", "360杀毒");
		dfmap.put("360rp.exe", "360杀毒");
		dfmap.put("360safe.exe", "360安全卫士");
		dfmap.put("360tray.exe", "360实时保护");
		dfmap.put("liveupdate360.exe", "360更新程序");
		dfmap.put("zhudongfangyu.exe", "360主动防御");
		dfmap.put("safeboxTray.exe", "360保险箱保护程序");
		dfmap.put("360safebox.exe", "360保险箱主程序");
		dfmap.put("360skylarsvc.exe", "360天擎终端安全管理系统");
		dfmap.put("wdswfsafe.exe", "360杀毒-网盾");
		dfmap.put("QHActiveDefense.exe", "360国际版");
		dfmap.put("360EntMisc.exe", "360(奇安信)天擎");
		dfmap.put("360EntClient.exe", "天擎EDR Agent");
		dfmap.put("edr_sec_plan.exe", "深信服EDR Agent");
		dfmap.put("edr_monitor.exe", "深信服EDR Agent");
		dfmap.put("edr_agent.exe", "深信服EDR Agent");
		dfmap.put("ESCCControl.exe", "启明星辰天珣EDR Agent");
		dfmap.put("ESCC.exe", "启明星辰天珣EDR Agent");
		dfmap.put("ESAV.exe", "启明星辰天珣EDR Agent");
		dfmap.put("ESCCIndex.exe", "启明星辰天珣EDR Agent");
		dfmap.put("savmain.exe", "Sophos杀毒");
		dfmap.put("savprogress.exe", "Sophos杀毒");
		dfmap.put("Sophos UI.exe", "Sophos杀毒");
		dfmap.put("SophosCleanM.exe", "Sophos杀毒");
		dfmap.put("SophosFileScanner.exe", "Sophos杀毒");
		dfmap.put("SophosOsquery.exe", "Sophos杀毒");
		dfmap.put("SophosNtpService.exe", "Sophos杀毒");
		dfmap.put("SophosFS.exe", "Sophos File Scanner Service");
		dfmap.put("SophosHealth.exe", "Sophos Health Service");
		dfmap.put("SophosSafestore64.exe", "Sophos Safestore Service");
		dfmap.put("SEDService.exe", "Sophos Endpoint Defense Service");
		dfmap.put("ALsvc.exe", "Sophos AutoUpdate Service");
		dfmap.put("SophosCleanM64.exe", "Sophos Clean Service");
		dfmap.put("McsAgent.exe", "Sophos MCS Agent");
		dfmap.put("McsClient.exe", "Sophos MCS Client");
		dfmap.put("SSPService.exe", "Sophos System Protection Service");
		dfmap.put("swc_service.exe", "Sophos Web Control Service");
		dfmap.put("SophosFIMService.exe", "Sophos FIM");
		dfmap.put("sdcservice.exe", "Sophos Device Control Service");
		dfmap.put("mbam.exe", "malwarebytes杀毒");
		dfmap.put("mbamtray.exe", "malwarebytes杀毒");
		dfmap.put("mbamservice.exe", "malwarebytes杀毒");
		dfmap.put("tmbmsrv.exe", "pc-cillin趋势反病毒");
		dfmap.put("ntrtscan.exe", "pc-cillin趋势反病毒");
		dfmap.put("vstskmgr.exe", "mcafee(麦咖啡)");
		dfmap.put("mcshield.exe", "mcafee(麦咖啡)");
		dfmap.put("mfevtps.exe", "mcafee(麦咖啡)");
		dfmap.put("mfeann.exe", "mcafee(麦咖啡)");
		dfmap.put("tbmon.exe", "mcafee(麦咖啡)");
		dfmap.put("shstat.exe", "mcafee(麦咖啡)");
		dfmap.put("mctray.exe", "mcafee(麦咖啡)");
		dfmap.put("udaterui.exe", "mcafee(麦咖啡)");
		dfmap.put("naprdmgr.exe", "mcafee(麦咖啡)");
		dfmap.put("engineserver.exe", "mcafee(麦咖啡)");
		dfmap.put("frameworkservice.exe", "mcafee(麦咖啡)");
		dfmap.put("avk.exe", "gdata安全防护软件");
		dfmap.put("gdscan.exe", "gdata安全防护软件");
		dfmap.put("avkwctl.exe", "gdata安全防护软件");
		dfmap.put("avkcl.exe", "gdata安全防护软件");
		dfmap.put("avkproxy.exe", "gdata安全防护软件");
		dfmap.put("avkbackupservice.exe", "gdata安全防护软件");
		dfmap.put("ccevtmgr.exe", "symantec(赛门铁克)");
		dfmap.put("ccsetmgr.exe", "symantec(赛门铁克)");
		dfmap.put("ccsvchst.exe", "symantec(赛门铁克) 或 norton(诺顿杀毒)");
		dfmap.put("rtvscan.exe", "symantec(赛门铁克) 或 norton(诺顿杀毒)");
		dfmap.put("smc.exe", "symantec(赛门铁克)");
		dfmap.put("smcgui.exe", "symantec(赛门铁克)");
		dfmap.put("snac.exe", "symantec(赛门铁克)");
		dfmap.put("symcorpui.exe", "symantec(赛门铁克)");
		dfmap.put("msmpeng.exe", "windows defender");
		dfmap.put("nissrv.exe", "windows defender");
		dfmap.put("mssense.exe", "windows defender");
		dfmap.put("msseces.exe", "windows defender");
		dfmap.put("mpcmdrun.exe", "windows defender");
		dfmap.put("msascui.exe", "windows defender");
		dfmap.put("msascuil.exe", "windows defender");
		dfmap.put("securityhealthservice.exe", "windows defender");
		dfmap.put("smartscreen.exe", "windows defender smartscreen");
		dfmap.put("avp.exe", "kaspersky(卡巴斯基)");
		dfmap.put("kavfs.exe", "kaspersky(卡巴斯基)");
		dfmap.put("klnagent.exe", "kaspersky(卡巴斯基)");
		dfmap.put("kavtray.exe", "kaspersky(卡巴斯基)");
		dfmap.put("kavfswp.exe", "kaspersky(卡巴斯基)");
		dfmap.put("ekrn.exe", "eset nod32防毒");
		dfmap.put("egui.exe", "eset nod32防毒");
		dfmap.put("eshasrv.exe", "eset nod32防毒");
		dfmap.put("eguiproxy.exe", "eset nod32防毒");
		dfmap.put("avg.exe", "avg杀毒");
		dfmap.put("avgwdsvc.exe", "avg杀毒");
		dfmap.put("avastui.exe", "avast!5主程序");
		dfmap.put("ashdisp.exe", "avast网络安全");
		dfmap.put("clamtray.exe", "clemwin free antivirus");
		dfmap.put("clamscan.exe", "clemwin free antivirus");
		dfmap.put("avcenter.exe", "avira(小红伞)");
		dfmap.put("avguard.exe", "avira(小红伞)");
		dfmap.put("avgnt.exe", "avira(小红伞)");
		dfmap.put("sched.exe", "avira(小红伞)");
		dfmap.put("bddownloader.exe", "百度卫士");
		dfmap.put("baidusafetray.exe", "百度卫士");
		dfmap.put("baiduansvx.exe", "百度卫士-主进程");
		dfmap.put("baidusd.exe", "百度杀毒-主程序");
		dfmap.put("baidusdsvc.exe", "百度杀毒-服务进程");
		dfmap.put("baidusdtray.exe", "百度杀毒-托盘进程");
		dfmap.put("f-prot.exe", "f-prot杀毒");
		dfmap.put("vba32lder.exe", "vb32杀毒");
		dfmap.put("k7tsecurity.exe", "k7杀毒");
		dfmap.put("iptray.exe", "immunet杀毒");
		dfmap.put("cmctrayicon.exe", "cmc杀毒");
		dfmap.put("bkavservice.exe", "bkav杀毒");
		dfmap.put("nspupsvc.exe", "nprotect杀毒");
		dfmap.put("a2guard.exe", "a-squared杀毒");
		dfmap.put("ad-watch.exe", "lavasoft杀毒");
		dfmap.put("unthreat.exe", "unthreat杀毒");
		dfmap.put("psafesystray.exe", "psafe反病毒");
		dfmap.put("patray.exe", "ahnlab安博士杀毒");
		dfmap.put("v3svc.exe", "ahnlab安博士v3杀毒");
		dfmap.put("cleaner8.exe", "the cleaner杀毒");
		dfmap.put("mongoosagui.exe", "mongoosa杀毒");
		dfmap.put("secenter.exe", "bitdefender杀毒");
		dfmap.put("ayagent.exe", "alyac韩国胶囊杀毒");
		dfmap.put("ksafe.exe", "金山卫士");
		dfmap.put("kvmonxp.exe", "江民杀毒");
		dfmap.put("ravmon.exe", "瑞星杀毒");
		dfmap.put("ravmond.exe", "瑞星杀毒");
		dfmap.put("kxescore.exe", "金山毒霸");
		dfmap.put("kupdata.exe", "金山毒霸");
		dfmap.put("kxetray.exe", "金山毒霸");
		dfmap.put("kwsprotect64.exe", "金山毒霸");
		dfmap.put("ksafetray.exe", "金山卫士");
		dfmap.put("knsdtray.exe", "可牛杀毒");
		dfmap.put("sbamsvc.exe", "vipre杀毒");
		dfmap.put("remupd.exe", "熊猫卫士杀毒");
		dfmap.put("spidernt.exe", "dr.web杀毒");
		dfmap.put("quhlpsvc.exe", "quickheal杀毒");
		dfmap.put("fsavgui.exe", "f-secure冰岛杀毒");
		dfmap.put("f-secure.exe", "f-secure冰岛杀毒");
		dfmap.put("arcatasksservice.exe", "arcavir杀毒");
		dfmap.put("vsserv.exe", "bitdefender比特梵德杀毒");
		dfmap.put("avwatchservice.exe", "virusfighter杀毒");
		dfmap.put("ns.exe", "norton诺顿杀毒");
		dfmap.put("ccapp.exe", "norton诺顿杀毒");
		dfmap.put("vptray.exe", "norton病毒防火墙-盾牌图标程序");
		dfmap.put("npfmntor.exe", "norton杀毒软件相关进程");
		dfmap.put("ccregvfy.exe", "norton杀毒软件自身完整性检查程序");
		dfmap.put("sndsrvc.exe", "symantec shared诺顿邮件防火墙软件");
		dfmap.put("spbbcsvc.exe", "symantec shared诺顿邮件防火墙软件");
		dfmap.put("symlcsvc.exe", "symantec shared诺顿邮件防火墙软件");
		dfmap.put("coranticontrolcenter32.exe", "coranti2012杀毒");
		dfmap.put("cksoftshiedantivirus4.exe", "shield antivirus杀毒");
		dfmap.put("spywareterminatorshield.exe", "spywareterminator杀毒");
		dfmap.put("usbkiller.exe", "u盘杀毒专家");
		dfmap.put("ast.exe", "超级巡警");
		dfmap.put("fortitray.exe", "飞塔");
		dfmap.put("gg.exe", "巨盾网游安全盾");
		dfmap.put("adam.exe", "绿鹰安全精灵");
		dfmap.put("kpfwtray.exe", "金山网镖");
		dfmap.put("beikesan.exe", "贝壳云安全");
		dfmap.put("parmor.exe", "木马克星");
		dfmap.put("iparmor.exe", "木马克星");
		dfmap.put("kswebshield.exe", "金山网盾");
		dfmap.put("trojanhunter.exe", "木马猎手");
		dfmap.put("webscanx.exe", "网络病毒克星");
		dfmap.put("ananwidget.exe", "墨者安全专家");
		dfmap.put("pfw.exe", "天网防火墙");
		dfmap.put("cfp.exe", "comodo科摩多");
		dfmap.put("mpmon.exe", "微点主动防御");
		dfmap.put("rfwmain.exe", "瑞星防火墙");
		dfmap.put("sphinx.exe", "sphinx防火墙");
		dfmap.put("vsmon.exe", "zonealarm防火墙");
		dfmap.put("fyfirewall.exe", "风云防火墙");
		dfmap.put("acs.exe", "outpost防火墙");
		dfmap.put("outpost.exe", "outpost防火墙");
		dfmap.put("avgaurd.exe", "avira antivir");
		dfmap.put("cpf.exe", "comodo");
		dfmap.put("emet_agent.exe", "emet");
		dfmap.put("emet_service.exe", "emet");
		dfmap.put("avconsol.exe", "mcafee");
		dfmap.put("avsynmgr.exe", "mcafee");
		dfmap.put("cpd.exe", "mcafee");
		dfmap.put("firesvc.exe", "mcafee");
		dfmap.put("firetray.exe", "mcafee");
		dfmap.put("hipsvc.exe", "mcafee");
		dfmap.put("mcafeefire.exe", "mcafee");
		dfmap.put("mcscript.exe", "mcafee");
		dfmap.put("updaterui.exe", "mcafee");
		dfmap.put("cleanup.exe", "mcafee");
		dfmap.put("cmdagent.exe", "mcafee");
		dfmap.put("frminst.exe", "mcafee");
		dfmap.put("mcscript_inuse.exe", "mcafee");
		dfmap.put("alogserv.exe", "mcafee virusscan");
		dfmap.put("_avp32.exe", "卡巴斯基");
		dfmap.put("_avpcc.exe", "卡巴斯基");
		dfmap.put("_avpm.exe", "卡巴斯基");
		dfmap.put("alertsvc.exe", "norton antivirus");
		dfmap.put("anti-trojan.exe", "anti-trojan elite");
		dfmap.put("arr.exe", "application request route");
		dfmap.put("atguard.exe", "antivir");
		dfmap.put("atwatch.exe", "mustek");
		dfmap.put("au.exe", "nsis");
		dfmap.put("aupdate.exe", "symantec");
		dfmap.put("autodown.exe", "antivirus autoupdater");
		dfmap.put("aavgapi.exe", "avg");
		dfmap.put("avgcc32.exe", "avg");
		dfmap.put("avgctrl.exe", "avg");
		dfmap.put("avgemc.exe", "avg");
		dfmap.put("avgrsx.exe", "avg");
		dfmap.put("avgserv.exe", "avg");
		dfmap.put("avgserv9.exe", "avg");
		dfmap.put("avgw.exe", "avg");
		dfmap.put("avkpop.exe", "g data software ag");
		dfmap.put("avkserv.exe", "g data software ag");
		dfmap.put("avkservice.exe", "g data software ag");
		dfmap.put("avkwctl9.exe", "g data software ag");
		dfmap.put("avltmain.exe", "panda software aplication");
		dfmap.put("avnt.exe", "h+bedv datentechnik gmbh");
		dfmap.put("avpdos32.exe", "kaspersky antivirus");
		dfmap.put("avpm.exe", "kaspersky antivirus");
		dfmap.put("avptc32.exe", "kaspersky antivirus");
		dfmap.put("avpupd.exe", "kaspersky antivirus");
		dfmap.put("avwin.exe", "h+bedv");
		dfmap.put("bargains.exe", "exact advertising spyware");
		dfmap.put("beagle.exe", "avast");
		dfmap.put("blackd.exe", "blackice");
		dfmap.put("blackice.exe", "blackice");
		dfmap.put("blink.exe", "micromedia");
		dfmap.put("blss.exe", "cblaster");
		dfmap.put("bootwarn.exe", "symantec");
		dfmap.put("bpc.exe", "grokster");
		dfmap.put("brasil.exe", "exact advertising");
		dfmap.put("ccevtmgr.exe", "norton internet security");
		dfmap.put("cdp.exe", "cyberlink corp.");
		dfmap.put("cfd.exe", "motive communications");
		dfmap.put("cfgwiz.exe", "norton antivirus");
		dfmap.put("clean.exe", "windows流氓软件清理大师");
		dfmap.put("cleaner.exe", "windows流氓软件清理大师");
		dfmap.put("cleaner3.exe", "windows流氓软件清理大师");
		dfmap.put("cleanpc.exe", "windows流氓软件清理大师");
		dfmap.put("defalert.exe", "symantec");
		dfmap.put("defscangui.exe", "symantec");
		dfmap.put("defwatch.exe", "norton antivirus");
		dfmap.put("dpps2.exe", "panicware");
		dfmap.put("dssagent.exe", "broderbund");
		dfmap.put("emsw.exe", "alset inc");
		dfmap.put("ethereal.exe", "rationalclearcase");
		dfmap.put("fast.exe", "fastusr");
		dfmap.put("fch32.exe", "f-secure");
		dfmap.put("fih32.exe", "f-secure");
		dfmap.put("findviru.exe", "f-secure");
		dfmap.put("firewall.exe", "ashampoosoftware");
		dfmap.put("fnrb32.exe", "f-secure");
		dfmap.put("fp-win.exe", "f-prot antivirus ondemand");
		dfmap.put("fsaa.exe", "f-secure");
		dfmap.put("fsav.exe", "f-secure");
		dfmap.put("fsav32.exe", "f-secure");
		dfmap.put("fsav530stbyb.exe", "f-secure");
		dfmap.put("fsav530wtbyb.exe", "f-secure");
		dfmap.put("fsav95.exe", "f-secure");
		dfmap.put("fsgk32.exe", "f-secure");
		dfmap.put("fsm32.exe", "f-secure");
		dfmap.put("fsma32.exe", "f-secure");
		dfmap.put("fsmb32.exe", "f-secure");
		dfmap.put("guard.exe", "ewido");
		dfmap.put("guarddog.exe", "ewido");
		dfmap.put("htpatch.exe", "silicon integrated systems corporation");
		dfmap.put("iamapp.exe", "symantec");
		dfmap.put("iamserv.exe", "symantec");
		dfmap.put("iamstats.exe", "symantec");
		dfmap.put("iedriver.exe", "urlblaze.com");
		dfmap.put("iface.exe", "panda antivirus module");
		dfmap.put("infus.exe", "infus dialer");
		dfmap.put("infwin.exe", "msviewparasite");
		dfmap.put("intdel.exe", "inet delivery");
		dfmap.put("keenvalue.exe", "euniverse inc");
		dfmap.put("launcher.exe", "intercort systems");
		dfmap.put("ldscan.exe", "windows trojans inspector");
		dfmap.put("luall.exe", "symantec");
		dfmap.put("luau.exe", "symantec");
		dfmap.put("lucomserver.exe", "norton");
		dfmap.put("mcagent.exe", "mcafee");
		dfmap.put("mcmnhdlr.exe", "mcafee");
		dfmap.put("mctool.exe", "mcafee");
		dfmap.put("mcupdate.exe", "mcafee");
		dfmap.put("mcvsrte.exe", "mcafee");
		dfmap.put("mcvsshld.exe", "mcafee");
		dfmap.put("mfin32.exe", "myfreeinternetupdate");
		dfmap.put("mfw2en.exe", "myfreeinternetupdate");
		dfmap.put("mfweng3.02d30.exe", "myfreeinternetupdate");
		dfmap.put("mgavrtcl.exe", "mcafee");
		dfmap.put("mgavrte.exe", "mcafee");
		dfmap.put("mghtml.exe", "mcafee");
		dfmap.put("mgui.exe", "bullguard");
		dfmap.put("mmod.exe", "ezulainc");
		dfmap.put("mostat.exe", "wurldmediainc");
		dfmap.put("mpfagent.exe", "mcafee");
		dfmap.put("mpfservice.exe", "mcafee");
		dfmap.put("mpftray.exe", "mcafee");
		dfmap.put("mscache.exe", "integrated search technologies spyware");
		dfmap.put("mscman.exe", "odysseusmarketinginc");
		dfmap.put("msmgt.exe", "total velocity spyware");
		dfmap.put("msvxd.exe", "w32/datom-a");
		dfmap.put("nav.exe", "reuters limited");
		dfmap.put("navapsvc.exe", "norton antivirus");
		dfmap.put("navapw32.exe", "norton antivirus");
		dfmap.put("navw32.exe", "norton antivirus");
		dfmap.put("ndd32.exe", "诺顿磁盘医生");
		dfmap.put("nisserv.exe", "norton");
		dfmap.put("nisum.exe", "norton");
		dfmap.put("nmain.exe", "norton");
		dfmap.put("nprotect.exe", "symantec");
		dfmap.put("npscheck.exe", "norton");
		dfmap.put("npssvc.exe", "norton");
		dfmap.put("outpostinstall.exe", "outpost");
		dfmap.put("patch.exe", "趋势科技");
		dfmap.put("pcscan.exe", "趋势科技");
		dfmap.put("persfw.exe", "tiny personal firewall");
		dfmap.put("pgmonitr.exe", "promulgate spyware");
		dfmap.put("pop3trap.exe", "pc-cillin");
		dfmap.put("poproxy.exe", "nortonantivirus");
		dfmap.put("powerscan.exe", "integrated search technologies");
		dfmap.put("prizesurfer.exe", "prizesurfer");
		dfmap.put("prmt.exe", "opistat");
		dfmap.put("prmvr.exe", "adtomi");
		dfmap.put("processmonitor.exe", "sysinternals");
		dfmap.put("protectx.exe", "protectx");
		dfmap.put("qconsole.exe", "norton antivirus quarantine console");
		dfmap.put("qserver.exe", "norton internet security");
		dfmap.put("rapapp.exe", "blackice");
		dfmap.put("rb32.exe", "rapidblaster");
		dfmap.put("rcsync.exe", "prizesurfer");
		dfmap.put("realmon.exe", "realmon");
		dfmap.put("rescue32.exe", "卡巴斯基互联网安全套装");
		dfmap.put("rtvscn95.exe", "real-time virus scanner");
		dfmap.put("rulaunch.exe", "mcafee user interface");
		dfmap.put("run32dll.exe", "pal pc spy");
		dfmap.put("safeweb.exe", "psafe tecnologia");
		dfmap.put("sbserv.exe", "norton antivirus");
		dfmap.put("sfc.exe", "system file checker");
		dfmap.put("sh.exe", "mks toolkit for win3");
		dfmap.put("showbehind.exe", "microsmarts enterprise component");
		dfmap.put("soap.exe", "system soap pro");
		dfmap.put("supporter5.exe", "escorcher反病毒");
		dfmap.put("symproxysvc.exe", "symantec");
		dfmap.put("symtray.exe", "symantec");
		dfmap.put("tbscan.exe", "thunderbyte");
		dfmap.put("tc.exe", "timecalende");
		dfmap.put("titanin.exe", "titanhide");
		dfmap.put("tvmd.exe", "total velocity");
		dfmap.put("tvtmd.exe", "total velocity");
		dfmap.put("vettray.exe", "etrust");
		dfmap.put("vpc32.exe", "symantec");
		dfmap.put("vpc42.exe", "symantec");
		dfmap.put("vshwin32.exe", "mcafee");
		dfmap.put("vsmain.exe", "mcafee");
		dfmap.put("vsstat.exe", "mcafee");
		dfmap.put("zapro.exe", "zone alarm");
		dfmap.put("zonealarm.exe", "zone alarm");
		dfmap.put("a2cmd.exe", "emsisoft anti-malware");
		dfmap.put("a2service.exe", "a-squared free");
		dfmap.put("a2free.exe", "a-squared free");
		dfmap.put("advchk.exe", "norton antivirus");
		dfmap.put("agb.exe", "安天防线");
		dfmap.put("ahprocmonserver.exe", "安天防线");
		dfmap.put("airdefense.exe", "airdefense");
		dfmap.put("avira.exe", "小红伞杀毒");
		dfmap.put("amon.exe", "tiny personal firewall");
		dfmap.put("avz.exe", "avz");
		dfmap.put("apvxdwin.exe", "熊猫卫士");
		dfmap.put("ashmaisv.exe", "alwil");
		dfmap.put("ashserv.exe", "avast anti-virus");
		dfmap.put("ashsimpl.exe", "avast!viruscleaner");
		dfmap.put("ashwebsv.exe", "avast");
		dfmap.put("aswupdsv.exe", "avast");
		dfmap.put("aswscan.exe", "avast");
		dfmap.put("avciman.exe", "熊猫卫士");
		dfmap.put("avengine.exe", "熊猫卫士");
		dfmap.put("avesvc.exe", "avira antivir security service");
		dfmap.put("avgchsvx.exe", "avg");
		dfmap.put("avgcsrvx.exe", "avg");
		dfmap.put("avgnsx.exe", "avg");
		dfmap.put("avgfwsrv.exe", "avg");
		dfmap.put("avgntmgr.exe", "avg");
		dfmap.put("avgtray.exe", "avg");
		dfmap.put("avgupsvc.exe", "avg");
		dfmap.put("avinitnt.exe", "command antivirus for nt server");
		dfmap.put("avserver.exe", "kerio mailserver");
		dfmap.put("avsched32.exe", "h+bedv");
		dfmap.put("avwupsrv.exe", "h+bedv");
		dfmap.put("bdswitch.exe", "bitdefender module");
		dfmap.put("clamwin.exe", "clamwin portable");
		dfmap.put("cureit.exe", "drweb cureit");
		dfmap.put("drwadins.exe", "dr.web");
		dfmap.put("drweb.exe", "dr.web");
		dfmap.put("defenderdaemon.exe", "shadowdefender");
		dfmap.put("ewidoctrl.exe", "ewido security suite");
		dfmap.put("ezantivirusregistrationcheck.exe", "e-trust antivirus");
		dfmap.put("fprottray.exe", "f-prot antivirus");
		dfmap.put("fpwin.exe", "verizon");
		dfmap.put("freshclam.exe", "clamav");
		dfmap.put("fsbwsys.exe", "f-secure");
		dfmap.put("fsdfwd.exe", "f-secure");
		dfmap.put("fsgk32st.exe", "f-secure");
		dfmap.put("fssm32.exe", "f-secure");
		dfmap.put("guardgui.exe", "网游保镖");
		dfmap.put("guardnt.exe", "ikarus");
		dfmap.put("inocit.exe", "etrust");
		dfmap.put("inorpc.exe", "etrust");
		dfmap.put("inort.exe", "etrust");
		dfmap.put("inotask.exe", "etrust");
		dfmap.put("inouptng.exe", "etrust");
		dfmap.put("isafe.exe", "etrust");
		dfmap.put("kav.exe", "kaspersky");
		dfmap.put("kavmm.exe", "kaspersky");
		dfmap.put("kavpf.exe", "kaspersky");
		dfmap.put("kazza.exe", "kaspersky");
		dfmap.put("kavpfw.exe", "kaspersky");
		dfmap.put("kavstart.exe", "kaspersky");
		dfmap.put("kavsvc.exe", "kaspersky");
		dfmap.put("kavsvcui.exe", "kaspersky");
		dfmap.put("kmailmon.exe", "金山毒霸");
		dfmap.put("mcregwiz.exe", "mcafee");
		dfmap.put("minilog.exe", "zone alarm");
		dfmap.put("myagtsvc.exe", "mcafee");
		dfmap.put("myagttry.exe", "mcafee");
		dfmap.put("navlu32.exe", "norton");
		dfmap.put("neowatchlog.exe", "neowatch");
		dfmap.put("neowatchtray.exe", "neowatch");
		dfmap.put("nod32.exe", "eset nod32");
		dfmap.put("npfmsg.exe", "norman个人防火墙");
		dfmap.put("nsmdtr.exe", "norton");
		dfmap.put("ofcpfwsvc.exe", "officescannt");
		dfmap.put("op_mon.exe", "outpostfirewall");
		dfmap.put("pavfires.exe", "熊猫卫士");
		dfmap.put("pavfnsvr.exe", "熊猫卫士");
		dfmap.put("pavkre.exe", "熊猫卫士");
		dfmap.put("pavprot.exe", "熊猫卫士");
		dfmap.put("pavproxy.exe", "熊猫卫士");
		dfmap.put("pavprsrv.exe", "熊猫卫士");
		dfmap.put("pavsrv51.exe", "熊猫卫士");
		dfmap.put("pavss.exe", "熊猫卫士");
		dfmap.put("pccguide.exe", "pc-cillin");
		dfmap.put("pcciomon.exe", "pc-cillin");
		dfmap.put("pccntmon.exe", "pc-cillin");
		dfmap.put("pccpfw.exe", "趋势科技");
		dfmap.put("pcctlcom.exe", "趋势科技");
		dfmap.put("pctav.exe", "pc tools antivirus");
		dfmap.put("pestpatrol.exe", "ikarus");
		dfmap.put("prevsrv.exe", "熊猫卫士");
		dfmap.put("savadminservice.exe", "sav");
		dfmap.put("savmain.exe", "sav");
		dfmap.put("savscan.exe", "sav");
		dfmap.put("sdhelp.exe", "spyware doctor");
		dfmap.put("spidercpl.exe", "dr.web");
		dfmap.put("spiderml.exe", "dr.web");
		dfmap.put("spiderui.exe", "dr.web");
		dfmap.put("spybotsd.exe", "spybot");
		dfmap.put("swagent.exe", "sonicwall");
		dfmap.put("swdoctor.exe", "sonicwall");
		dfmap.put("swnetsup.exe", "sophos");
		dfmap.put("symsport.exe", "sysmantec");
		dfmap.put("symwsc.exe", "sysmantec");
		dfmap.put("synmgr.exe", "sysmantec");
		dfmap.put("tmlisten.exe", "趋势科技");
		dfmap.put("tmntsrv.exe", "趋势科技");
		dfmap.put("tmproxy.exe", "趋势科技");
		dfmap.put("tnbutil.exe", "anti-virus");
		dfmap.put("vcrmon.exe", "viruschaser");
		dfmap.put("vrmonnt.exe", "hauri");
		dfmap.put("vrmonsvc.exe", "hauri");
		dfmap.put("xcommsvr.exe", "bitdefender");
		dfmap.put("afwserv.exe", "avast antivirus");
		dfmap.put("ksafesvc.exe", "金山毒霸");
		dfmap.put("kwatch.exe", "金山毒霸");
		dfmap.put("scan32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("aawtray.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ad-aware.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ackwin32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("adaware.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("advxdwin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("agentsvr.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("agentw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("alevir.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("amon9x.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("antivirus.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ants.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("apimonitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("aplica32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("atcon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("atro55en.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("atupdater.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("auto-protect.nav80try.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("autotrace.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("autoupdate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ave32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avp32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avpcc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avwin95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avwinnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avwupd.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avwupd32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avxmonitor9x.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avxmonitornt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avxquar.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("backweb.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bd_professional.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("belt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bidef.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bidserver.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bipcp.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bipcpevalsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bisp.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bootconf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("borg2.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bs120.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bundle.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bvt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ccpxysvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cfiadmin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cfiaudit.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cfinet.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cfinet32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("claw95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("claw95cf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("click.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cmesys.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cmgrdian.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cmon016.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("connectionmonitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cpf9x206.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cpfnt206.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ctrl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cwnb181.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cwntdwmo.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("datemanager.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dcomx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("deputy.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("divx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dllcache.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dllreg.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("doors.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dpf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dpfsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("drwatson.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("drweb32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("drwebupw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dvp95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dvp95_0.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ecengine.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("efpeadm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ent.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("esafe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("escanhnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("escanv95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("espwatch.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("etrustcipe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("evpn.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("exantivirus-cnet.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("exe.avxw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("expert.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("explore.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("f-agnt95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("f-prot95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("f-stopw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fameh32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fp-win_trial.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fprot.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("frw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fsgk32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gator.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gbmenu.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gbpoll.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("generics.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gmt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hacktracersetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hbinst.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hbsrv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hotactio.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hotpatch.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("htlog.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hwpe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hxdl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hxiul.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ibmasn.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ibmavsp.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icload95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icloadnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icmon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icsupp95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icsuppnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("idle.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("iedll.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ifw2000.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("inetlnfo.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("init.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("intren.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("iomon98.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("istsvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("jammer.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("jdbgmrg.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("jedi.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kavlite40eng.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kavpers40eng.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kerio-pf-213-en-win.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kerio-wrl-421-en-win.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kerio-wrp-421-en-win.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("kernel32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("killprocesssetup161.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ldnetmon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ldpro.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ldpromenu.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lnetinfo.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("loader.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("localnet.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lockdown.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lockdown2000.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lookout.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lordpe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("lsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("luinit.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("luspt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mapisvc32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("md.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("monitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("moolive.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mrflux.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msapp.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msbb.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msblast.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msccn32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msconfig.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msdm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msdos.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msinfo32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mslaugh.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("msmsgri32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mssmmc32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mssys.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mu0311ad.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mwatch.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("n32scanw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("navap.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("navdx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("navnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("navstub.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("navwnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nc2000.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ncinst4.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("neomonitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netarmor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netd32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netinfo.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netmon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netscanpro.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netspyhunter-1.2.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netstat.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("netutils.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("normist.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("norton_internet_secu_3.0_407.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("notstart.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("npf40_tw_98_nt_me_2k.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("npfmessenger.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nsched32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nssys32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nstask32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nsupdate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ntvdm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ntxconfig.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nui.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nupgrade.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvarch16.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvc95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvsvc32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nwinst4.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nwservice.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nwtool16.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ollydbg.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("onsrvr.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("optimize.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ostronet.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("otfix.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("outpostproinstall.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("padmin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("panixk.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pavcl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pavsched.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pavw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pccwin98.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pcfwallicon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pcip10117_0.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pdsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("periscope.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("perswf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pf2.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pfwadmin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pingscan.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("platin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("popscan.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("portdetective.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("portmonitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ppinupdt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pptbc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ppvstop.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("procdump.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("procexplorerv1.0.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("programauditor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("proport.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pspf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("purge.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rav7.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rav7win.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rav8win32eng.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ray.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("reged.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("regedit.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("regedt32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rescue.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rrguard.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rshell.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rundll.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("rundll16.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ruxdll32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sahagent.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("save.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("savenow.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("scam32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("scan95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("scanpm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("serv95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("setup_flowprotector_us.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("setupvameeval.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sgssfw32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("shellspyinstall.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("shn.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sms.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("smss32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sofi.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sperm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("spf.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("spoler.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("spoolcv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("spoolsv32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("spyxx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("srng.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ss3edit.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ssg_4104.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ssgrate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("st2.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("start.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("stcloader.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("supftrl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("support.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("svchosts.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sweep95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sweepnet.sweepsrv.sys.swnetsup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sysedit.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sysupd.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("taskmg.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("taskmo.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("taumon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tca.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tcm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tds-3.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tds2-98.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tds2-nt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("teekids.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tfak.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tfak5.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tgbob.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("titaninxp.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tracert.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("trickler.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("trjscan.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("trjsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("trojantrap3.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("tsadbot.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("undoboot.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("updat.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("update.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("upgrad.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("utpost.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbcmserv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbcons.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbust.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbwin9x.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbwinntw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vcsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vet32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vet95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vfsetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vir-help.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("virusmdpersonalfirewall.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vnlan300.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vnpc3000.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vpfw30s.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vscan40.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vscenu6.02d30.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vsched.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vsecomr.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vsisetup.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vswin9xe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vswinntse.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vswinperse.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("w32dsm89.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("w9x.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("watchdog.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("webdav.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("webtrap.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wfindv32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("whoswatchingme.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wimmun32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("win-bugsfix.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("win32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("win32us.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winactive.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("window.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("windows.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wininetd.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wininitx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winlogin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winmain.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winnet.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winppr32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winrecon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winservn.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winssk32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winstart.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winstart001.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wintsk32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winupdate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wkufind.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wnad.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wradmin.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wrctrl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wsbgate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wupdater.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wupdt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("wyvernworksfirewall.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("xpf202en.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("zapsetup3001.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("zatutor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("zonalm2601.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("akrnl.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("trojan.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("antivir.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("armor2net.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ashenhcd.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ashpopwz.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ashskpck.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("aveval.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avevl32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avgam.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avgcc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("avxmonitor.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cafix.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("bitdefender.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("cfpconfig.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("drvirus.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dwebllio.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("dwebio.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("escanh95.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("filemon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("forticlient.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fortiscan.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fpavserver.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("f-sched.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("fspex.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gcasdtserv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("gcasserv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("giantantispyware.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("guardxservice.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("guardxkickoff.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hregmon.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hrres.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hsockpe.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("hupdate.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("icssuppnt.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("inetupd.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("isatray.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("mamutu.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("npavtray.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nssserv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nsstray.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("ntos.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvcod.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvcte.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("nvcut.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("onlinent.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("opssvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pcctlcom.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pertsk.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pervac.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("pnmsrv.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("prevx.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("psimsvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("qhonline.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("qhonsvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("qhwscsvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("qhset.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sality.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sapissvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("scanwscs.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("scanningprocess.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sdra64.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("sitecli.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("stopsignav.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vba32ecm.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vba32ifs.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vba32ldr.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vba32pp3.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vbsntw.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vrfwsvc.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("vrrw32.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("winssnotify.exe", "已知杀软进程,名称暂未收录");
		dfmap.put("zlclient.exe", "已知杀软进程,名称暂暂未收录");
		dfmap.put("chrome.exe", "谷歌浏览器");
		dfmap.put("firefox.exe", "火狐浏览器");
		dfmap.put("msedge.exe", "火狐浏览器");
		dfmap.put("Telegram.exe", "Telegram");
		dfmap.put("WeChat.exe", "微信客户端");
		dfmap.put("WeChatStore.exe", "微信客户端");
		dfmap.put("aDrive.exe", "阿里网盘");
		dfmap.put("pCloud.exe", "pCloud网盘");
		dfmap.put("baidunetdisk.exe", "百度网盘");
		dfmap.put("baidunetdiskhost.exe", "百度网盘");
		dfmap.put("baidunetdiskrender.exe", "百度网盘");
		dfmap.put("yundetectservice.exe", "百度云管家");
		dfmap.put("wps.exe", "WPSOffice办公套件");
		dfmap.put("wpscloudsvr.exe", "WPSOffice云服务");
		dfmap.put("AnyDesk.exe", "AD远程控制软件");
		dfmap.put("tv_w32.exe", "TV远程控制软件");
		dfmap.put("tv_x64.exe", "TV远程控制软件");
		dfmap.put("TeamViewer.exe", "TV远程控制软件");
		dfmap.put("TeamViewer_Service.exe", "TV远程控制软件");
		dfmap.put("SunloginClient.exe", "向日葵程控制软件");
		dfmap.put("ToDesk.exe", "ToDesk程控制软件");
		dfmap.put("ToDesk_Service.exe", "ToDesk服务");
		dfmap.put("ToDesk_Session.exe", "ToDesk会话");
		dfmap.put("ToDesk_Lite.exe", "ToDesk绿色版");
		dfmap.put("notepad++.exe", "Notepad++编辑器");
		dfmap.put("vmware.exe", "VMware虚拟机");
		dfmap.put("vmware-tray.exe", "VMware虚拟机");
		dfmap.put("vmware-vmx.exe", "VMware虚拟机");
		dfmap.put("vmware-authd.exe", "VMware虚拟机");
		dfmap.put("vmware-unity-helper.exe", "VMware虚拟机");
		dfmap.put("vmware-usbarbitrator64.exe", "VMware虚拟机");
		dfmap.put("VirtualBox.exe", "VirtualBox虚拟机");
		dfmap.put("VBoxSVC.exe", "VirtualBox虚拟机");
		dfmap.put("VBoxSDS.exe", "VirtualBox虚拟机");
		dfmap.put("SGTool.exe", "搜狗输入法-属性设置工具");
		dfmap.put("SGDownload.exe", "搜狗输入法-修复更新工具");
		dfmap.put("pinyinup.exe", "搜狗输入法-网络更新程序");
		dfmap.put("SogouCloud.exe", "搜狗输入法-云计算代理");
		dfmap.put("SogouComMgr.exe", "搜狗输入法-工具箱");
		dfmap.put("SGRender.exe", "搜狗输入法-用户登录");
		dfmap.put("QQPYUserCenter.exe", "QQ拼音输入法-个人中心");
		dfmap.put("QQPYLiveUp.exe", "QQ拼音输入法-升级工具");
		dfmap.put("QQPYConfig.exe", "QQ拼音输入法-属性设置");
		dfmap.put("QQPYToolbox.exe", "QQ拼音输入法-工具箱");
		dfmap.put("QQPYCloud.exe", "QQ拼音云输入-客户端");
		dfmap.put("HwsHostPanel.exe", "护卫神主机卫士");
		dfmap.put("HwsHostMaster.exe", "护卫神主机卫士");
		dfmap.put("建站助手V4.0.exe", "西部数码建站助手");
		dfmap.put("红帆自定义表单设计器.exe", "红帆OA");
		dfmap.put("gpstool.exe", "某GPS定位工具");
		dfmap.put("GServer.exe", "EXLIVE位置服务平台");
		dfmap.put("phpStudy.exe", "phpStudy集成环境");
		dfmap.put("xampp-control.exe", "XAMPP集成环境");
		dfmap.put("python.exe", "Python环境");
		dfmap.put("httpd.exe", "Apache环境");
		dfmap.put("nginx.exe", "Nginx环境");
		dfmap.put("mysql.exe", "MySQL数据库");
		dfmap.put("mysqld.exe", "MySQL数据库");
		dfmap.put("sqlservr.exe", "MSSQL数据库");
		dfmap.put("SQLAGENT90.EXE", "MSSQL代理服务");
		dfmap.put("mongod.exe", "MongoDB数据库");
		dfmap.put("SQL-Front.exe", "MySQL数据库管理工具");
		dfmap.put("SQLyogCommunity.exe", "SQLyogCommunity数据库管理工具");
		dfmap.put("navicat.exe", "Navicat数据库管理工具");
		dfmap.put("Ssms.exe", "SQL Server Management Studio");
		dfmap.put("sqlcmd.exe", "SQL Server命令行工具");
		dfmap.put("FileZilla Server.exe", "FileZilla Server-FTP");
		dfmap.put("FileZilla Server Interface.exe", "FileZilla Server-FTP");
		dfmap.put("ServUDaemon.exe", "Serv-U-FTP");
		dfmap.put("G6FTPServer.exe", "G6FTP-FTP");
		dfmap.put("G6FTPTray.exe", "G6FTP-FTP");
		dfmap.put("flashfxp.exe", "FlashFXP-FTP");
		dfmap.put("WinSCP.exe", "WinSCP-SSH");
		dfmap.put("hfs.exe", "Http File Server-HTTP");
		dfmap.put("Xshell.exe", "Xshell终端软件");
		dfmap.put("XshellCore.exe", "Xshell终端软件");
		dfmap.put("CloudClient.exe", "华为云桌面-客户端");
		dfmap.put("BtTools.exe", "宝塔面板Windows工具箱");
		dfmap.put("npc.exe", "内网穿透工具NPS客户端");
		dfmap.put("nps.exe", "内网穿透工具NPS服务端");
		dfmap.put("frpc.exe", "内网穿透工具FRP客户端");
		dfmap.put("frps.exe", "内网穿透工具FRP服务端");
		dfmap.put("finalshell.exe", "FinalShell SSH工具");
		dfmap.put("SangforUDProtectEx.exe", "深信服VPN升级程序");
		dfmap.put("SangforPromoteService.exe", "深信服VPN");
		dfmap.put("zabbix_agentd.exe", "Zabbix客户端");
	}

	public static List<String> query(String text){
		if (dfmap==null){
			init();
		}
		List<String> resultary = new ArrayList<String>();

		boolean flag = false;
		for (Map.Entry<String,String> entry:dfmap.entrySet()){
			if (text.toLowerCase().contains(entry.getKey().toLowerCase())){
				flag = true;
				resultary.add(entry.getKey());
				resultary.add(entry.getValue());
				break;
			}
		}
		return flag?resultary:null;
	}
}
